minamijoyo/myaws

- cmd/ec2.go
When I create a new EC2 instance, I can't find the instance using following command:
```bash
$ myaws ec2 ls --all --profile default --region us-east-1
```
`myaws` sets `Name:` as default value of tag filter, therefore if the instance does not have `Name` tag, the application can't find this instance.
In conclusion, I removed default value in tag filter.
> Remove default value in tag filter when use ec2 ls command

- myaws/ssm_parameter.go
- myaws/ssm_parameter_env.go
- myaws/ssm_parameter_get.go
The AWS SSM GetPrameters API can only get 10 parameters at once.
To get 10 or more parameters, we need to call API multiple time.
https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParameters.html
> Allow getting 10 or more ssm parameters

- myaws/ssm_parameter_env.go
If a value of SSM parameter has '%' character, `myaws ssm paramete env` outputs invalid string like `!(NOVERB)`.
> escape % character on ssm parameter env

- cmd/root.go
- myaws/client.go
- myaws/config.go
`github.com/aws/aws-sdk-go/aws/request.Waiter` doesn't provide useful logs,
so we simply log AWS API request and response in debug mode.
> Enable AWS API request and response logging in debug mode

- myaws/ec2_ssh.go
Using myaws ec2 ssh returns an error.
```
unable to connect:: ssh: must specify HostKeyCallback
```
This caused by a backwards incompatible change in `x/crypto/ssh`.
A `HostKeyCallback` param is now required.
See: https://github.com/golang/go/issues/19767
> ec2/ssh: Fix HostKeyCallback error

- myaws/ecs_node_renew.go
- myaws/ecs_waiter.go
I found that a stable state for all ECS services does not mean that all targets are healthy.
We need to explicitly confirm it.
> ecs/node/renew: Wait until alb target healthy

- myaws/ecs_node_drain.go
- myaws/ecs_node_renew.go
We can specify up to 10 container instances to update state in a single operation.
This constraint is not specified in the API reference, but it returns the following error:
InvalidParameterException: instanceIds can have at most 10 items.
So we need to divide the list by 10.
We also missed the error handling when ECSNodeDrain returns an error, so fixed it too.
> ecs/node/renew & drain: Wait until node drain on renew

- myaws/ecs_waiter.go
Timeouts sometimes occur with large workloads.
> ecs/node/drain: Extend wait timeout for drain

- Makefile
- go.mod
- go.sum
- myaws/ecs.go
- tools.go
The following was a bug fix for error handling at ecs node drain:
#25
But it should be checked by static analysis.
The `errcheck` cannot detect it, but `ineffassign` can. So we add `ineffassign` to `make check`.
I also fixed unchecked error in findECSNodes() found by ineffassign
> Add ineffassign to detect unchecked errors

- myaws/autoscaling_set_instance_protection.go
- myaws/ecs_node_renew.go
fixed https://github.com/minamijoyo/myaws/issues/28
In `myaws ecs node renew` command,
- set "scale-in protection" option for instances created at scale-out
- remove "scale-in protection" at scale-in
If "scale-in protection" is already set  in ASG settings, "scale-in protection" is not deleted at scale-in.
> fix termintate unintended instance on `ecs node renew`

- myaws/ssm_parameter.go
- myaws/ssm_parameter_env.go
There are two APIs to get the value of SSM Parameter Store: GetParameters and GetParametersByPath.
GetParameters: 
- Rate Limit is undocumented.
- It retrieves all values
GetParametersByPath
- Rate Limit is documented.
- We can specify level, and it recieves only values that have specified level.
This PR can use  GetParametersByPath API when running `myaws ssm parameter env` with name starts with slash.
As a result, even if there are many keys stored in SSM Parameter Store, the values can be obtained without being limited by Rate Limit.
> use GetParametersByPath instead of GetParameters when path started with slash on SSMParameterEnv

- cmd/ecs.go
- myaws/ecs.go
- myaws/ecs_node_ls.go
- myaws/ecs_service_ls.go
The current outputs is a bit ambiguous.
We want to add a header to outputs of `ecs status` command.
So we add `--print-header` option to `ecs node ls` and `ecs service ls`. 
`* ls` commands may use with `wc -l`, so its option default to false.
While adjusting outputs, I found a namespace of container instance is redundant (it seems to be always cluster name) and container instance id is missing which needs drain operation.
So we change outputs of `ecs node ls`. This is a breaking change.
> ecs/status: Print Header

- cmd/ecs.go
- myaws/ecs_node_renew.go
- myaws/ecs_service_update.go
- myaws/ecs_waiter.go
The official (*ECS) WaitUntilServicesStableWithContext has fixed MaxAttempts(40) and Delay(15),
this means we can't wait more than 10 minutes even if we pass the context.
So we wrap it and allow timeout with a given context.
I found it in `ecs service update`, but it also affects `ecs node renew`, so I fixed them.
> Extends wait timeout for ecs service stable

- cmd/ecs.go
- myaws/ecs_node_drain.go
- myaws/ecs_node_renew.go
- myaws/ecs_waiter.go
If we have a lot of containers on host, `ecs node renew` fails with a timeout in node drain phase. We should pass a context explicitly and timeout with the given context. We also add timeout flag to `ecs node drain` for consistency.
> ecs/node/drain: Allow to set timeout with a given context

- cmd/ecs.go
- myaws/ecs_service_update.go
When updating a ECS task definition, We want to deploy a new task with new revision.
The ECS UpdateService API doesn't update the revision without the TaskDefinition parameter.
To update the revision, we set only a task family without revision.
If a revision is not specified, the latest ACTIVE revision is used.
If the current task uses the latest ACTIVE one, it hasn't no side-effect.
Since the Force option expects to deploy and converge to the latest state,
when Force option is enabled, we implicitly fetch and set the task family.
> ecs/service/update: Fetch the latest task definition on force

- .goreleaser.yml
- cmd/version.go
The current docker image doesn't set a version number.
This is caused by setting it by goreleaser.
Let's make it the same way as any other my projects.
> Set a version number explicitly in source

- .github/workflows/docker.yaml
The Docker Hub recently stopped auto builds for free plan. We need to build and push docker images as a part of release process.
Breaking Changes:
The `latest` tag now points at the latest release. Previously the `latest` tag pointed at the master branch, if you want to use the master branch, use the `master` tag instead.
> Build & push docker images on GitHub Actions

- .github/workflows/docker.yaml
It's not suitable for building on pull request because it's required a credential for docker login.
> Remove docker build on pull request

- .goreleaser.yml
closes #53 
I use M1 MacBook air, and I couldn't install arm64 version of myaws.
So, I added release target to arm64 architecture.
In this settings, linux-arm64 also added release target.
This can ignore, but Raspberry Pi users can user this nice software.
So I don't exclude this.
https://goreleaser.com/customization/build/#builds
> Add release target to arm64 architecture

- cmd/ssm.go
- myaws/ssm_parameter_env.go
Fixes: #58
When values of the AWS SSM parameter store has blanks, `myaws ssm parameter env` does not work as expected.
https://github.com/minamijoyo/myaws/issues/58
So, I added new option `--quote`.
When this parameter is specified, each value wraps in single quote.
```shell
$ myaws ssm parameter put test.env.var '$HOME'
$ myaws ssm parameter put test.str.var 'foo'
$ myaws ssm parameter put test.arr.var 'a b c d'
$ bin/myaws ssm parameter env --help
Print SSM parameters as a list of environment variables
Usage:
myaws ssm parameter env NAME [flags]
Flags:
-e, --docker-format   Output in docker environment variables format such as -e KEY=VALUE
-h, --help            help for env
-q, --quote           Wrap each value in single quote
Global Flags:
--config string     config file (default …
```
> [ssm parameter env] add quote parameter

- .github/workflows/release.yaml
I found a misplaced hyphen in release.yaml.
This causes error on GitHub Actions.
https://github.com/minamijoyo/myaws/actions/runs/2152792350
> [github actions] fix checkout step
